---
abstract: 'parse reports to www.cpantesters.org from various sources'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-SawAmpersand
no_index:
  directory:
    - t
    - inc
provides:
  Devel::SawAmpersand:
    file: lib/Devel/SawAmpersand.pm
    version: 0.33
requires:
  CPAN::Meta::Converter: 2.110440
  Parse::CPAN::Meta: 1.4404
  Test::More: 0
version: 0.33
